name: GitHub release

on:
  push:
    branches:
      - 'main'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: install dart
      run: curl -sSL "https://raw.githubusercontent.com/tarsislimadev/debian/refs/heads/main/src/install/dart.sh" | bash
    
    - name: compile executable file
      run: |
          cd ./src/cli/
          dart pub add http
          dart pub get
          dart pub upgrade
          dart compile exe ./bin/binance.dart

    - name: create release
      run: gh release create v$( date +%Y%m%d%H%M ) ./src/cli/bin/binance.exe
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
